import sys
from pathlib import Path


WINDOW_NAME = "MouthClick"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
BUNDLE_ROOT = Path(getattr(sys, "_MEIPASS", PROJECT_ROOT))
MODEL_PATH = BUNDLE_ROOT / "models" / "face_landmarker.task"

NOSE_TIP_INDEX = 1
LEFT_EYE_POINTS = (362, 385, 387, 263, 373, 380)
RIGHT_EYE_POINTS = (33, 160, 158, 133, 153, 144)

DEFAULT_EYE_CLOSED_THRESHOLD = 0.20
CALIBRATION_SECONDS = 3.0
MIN_CALIBRATION_SAMPLES = 10
CALIBRATION_THRESHOLD_FACTOR = 0.70
MIN_BLINK_SECONDS = 0.05
MAX_BLINK_SECONDS = 0.45
BLINK_COOLDOWN_SECONDS = 0.35
BLINK_MESSAGE_SECONDS = 0.7

DOUBLE_BLINK_WINDOW_SECONDS = 0.8
SIMULATED_CLICK_COOLDOWN_SECONDS = 1.2
SIMULATED_CLICK_FEEDBACK_SECONDS = 0.7

CONTROL_AREA_WIDTH = 280
CONTROL_AREA_HEIGHT = 180
CONTROL_AREA_MARGIN = 20
DEFAULT_CURSOR_SENSITIVITY = 2.0
MIN_CURSOR_SENSITIVITY = 1.0
MAX_CURSOR_SENSITIVITY = 8.0
CURSOR_SMOOTHING = 0.20
VISUAL_CURSOR_BASE_MAX_STEP_PIXELS = 12.0
NOSE_DEAD_ZONE_PIXELS = 7.0

QUALITY_STABLE_FRAMES = 5
QUALITY_NOSE_JUMP_PIXELS = 42.0
QUALITY_MISSING_FACE_FRAMES = 3

UI_MARGIN = 10
UI_PANEL_MIN_WIDTH = 260
UI_PANEL_MAX_WIDTH = 360
UI_CONTROL_MIN_WIDTH = 180
UI_CONTROL_MIN_HEIGHT = 110

REAL_MOUSE_PAUSE_SECONDS = 0.02
REAL_MOUSE_SCREEN_MARGIN = 12
REAL_MOUSE_BASE_MAX_STEP_PIXELS = 45
REAL_CLICK_COOLDOWN_SECONDS = 1.5
REAL_CLICK_FEEDBACK_SECONDS = 0.8
TONGUE_CLICK_COOLDOWN_SECONDS = 1.4
TONGUE_FEEDBACK_SECONDS = 0.75
TONGUE_CALIBRATION_SECONDS = 2.0
TONGUE_MOUTH_OPEN_THRESHOLD = 0.22
TONGUE_COLOR_RATIO_THRESHOLD = 0.08
TONGUE_TRIGGER_FRAMES = 3
TONGUE_CURSOR_HOLD_SECONDS = 0.55
F8_KEY_CODES = (0x770000, 65477, 16777271)
F9_KEY_CODES = (0x780000, 65478, 16777272)
REAL_MOUSE_TOGGLE_KEYS = F8_KEY_CODES + (ord("m"), ord("M"))
LOCK_TOGGLE_KEYS = (ord("b"), ord("B"))
ESC_KEY_CODE = 27
